---
title: "irace_lcbench_07_05_single_b3000"
output: html_notebook
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = "~/Repository/paper_2021_benchmarking_special_issue/")
```

```{r, include = FALSE}
library(data.table)
library(ggplot2)
library(patchwork)
library(mlr3misc)
library(stringr)
library(knitr)

instance_file = "./irace/data/data_07_05_single_b3000/irace_instance.rda"
log_file = "./irace/data/data_07_05_single_b3000/irace_log.Rdata"

# load and fix
instance = readRDS(instance_file)
load(log_file)
archive = as.data.table(instance$archive)
archive$y = unlist(archive$y)
log = as.data.table(iraceResults$experimentLog) 

# ids
ids = c("x_domain_budget_log_step", "x_domain_mu", instance$search_space$ids()[3:12])

full_ids = c("x_domain_budget_log_step", "fidelity_steps_lcbench", "x_domain_mu", instance$search_space$ids()[3:12])

# add race to archive
archive$race = iraceResults$experimentLog[,1]

# aggregate archive
aggregated_archive = archive[, .(y = mean(y)), by = c("id_configuration", ids)]
aggregated_archive[,fidelity_steps_lcbench := floor((52-1)/x_domain_budget_log_step + 1)]
setcolorder(aggregated_archive, full_ids)

aggregated_elites = aggregated_archive[id_configuration %in% iraceResults$allElites[[6]],]
```

## stats

```{r, echo = FALSE}
tab = data.table(
  start = archive$timestamp[1],
  end = archive$timestamp[nrow(archive)],
  n_configurations = max(log$configuration),
  n_evals = nrow(log),
  n_races = length(iraceResults$allElites),
  n_elites = length(iraceResults$allElites[[length(iraceResults$allElites)]]),
  benchmark = "LCBench",
  optimization_target = "val_balanced_accuracy",
  test_target = "test_balanced_accuracy"
)
kable(tab)
```

## stats races

```{r, echo = FALSE}
tab = data.table(
  race = seq_along(iraceResults$allElites),
  n_configurations_start = map_int(seq_along(iraceResults$allElites), function(x) length(unique(archive[race == x, id_configuration]))),
  n_elites = map_int(iraceResults$allElites, length),
  elites = map(iraceResults$allElites, function(x) paste(x, collapse = ","))
)
kable(tab)
```

## marginal plots

```{r, echo = FALSE, fig.height = 20, fig.width = 30}
marginal_plot = function(parameter) {
  ggplot(aggregated_archive, aes_string(x = parameter, y = "y")) +
    geom_point(aes(color = id_configuration), size = 3) +
    geom_text(data = aggregated_elites, aes(label = id_configuration), hjust = -1,vjust = 1)
}

m_plots = lapply(ids, marginal_plot)
wrap_plots(m_plots)
```

## boxplot elites

```{r, echo = FALSE, fig.height = 20, fig.width = 30}
ggplot(archive[id_configuration %in% iraceResults$allElites[[6]],], aes(group = factor(id_configuration), x = factor(id_configuration), y = y)) +
  geom_boxplot()
```

## sampling frequency

```{r, echo = FALSE, fig.height = 20, fig.width = 30}
frequency_numeric_plot = function(parameter) {
  ggplot(archive, aes_string(x = parameter)) +
    geom_histogram(bins = 30) +
    geom_vline(data = aggregated_elites, aes_string(xintercept = parameter)) +
    geom_label(data = aggregated_elites, aes_string(x = parameter, label = "id_configuration"), y = 0)
}

frequency_categorical_plot = function(parameter) {
  ggplot(archive, aes_string(x = parameter)) +
    geom_bar()
}

m_plots_1 = lapply(ids[instance$search_space$is_number], frequency_numeric_plot)
m_plots_2 = lapply(ids[!instance$search_space$is_number], frequency_categorical_plot)
wrap_plots(c(m_plots_1, m_plots_2))
```

## best

```{r, echo = FALSE}
kable(aggregated_elites[id_configuration == instance$result$id_configuration,])
```

### elites

```{r, echo = FALSE}
kable(aggregated_elites)
```